// Reasons
export const FETCH_REASONS_STARTED = 'FETCH_REASONS_STARTED';
export const FETCH_REASONS_FULFILLED = 'FETCH_REASONS_FULFILLED';
export const FETCH_REASONS_REJECTED = 'FETCH_REASONS_REJECTED';

// Login
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
